BankingWebApplication/Models/EditRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BankingWebApplication.Models
{
    public class EditRoleViewModel
    {
        public List<SelectList> RolesList { get; set; }
        public string SelectedRole { get; set; }
        public int CustomerNo { get; set; }
        public string UserName { get; set; }


    }
}

BankingWebApplication/Areas/Identity/Pages/Account/Login.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace BankingWebApplication.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

      

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
    

            [Required]
            [DataType(DataType.Password)]
            [MaxLength(63)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }


            [Required]
            [MinLength(6)]
            [MaxLength(50)]
            public string UserName { get; set; }

     

        
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl = returnUrl ?? Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }




        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.UserName, Input.Password, Input.RememberMe, lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }



            // If we got this far, something failed, redisplay form
            return Page();
        }


    }
}

BankingWebApplication/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankingWebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;
using DAL.Entities;
using BusinessLayer;
using DAL.Enum;
using Microsoft.AspNetCore.Http;

namespace BankingWebApplication.Controllers
{
    public class AccountsController : Controller
    {
        static IAccount ca;
        static IAccount ba;
        static IAccount la;
        static IAccount td;
        private readonly ApplicationDbContext _context;

        AccountBL accountbl = new AccountBL();
        CustomerBL customerBl = new CustomerBL();

        public AccountsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Accounts/{Customer No}
        public async Task<IActionResult> Index(int? id)
        {
            if (HttpContext.Session.GetString("CustomerNo") != null)
            {
                string header = "All Accounts";
                if (id == null && HttpContext.Session.GetString("UserRole") == RoleEnum.Customer.ToString())
                {
                    id = int.Parse(HttpContext.Session.GetString("CustomerNo"));
                }
                if (id != null)
                {
                    var customer = customerBl.GetCustomerFromCustomerNo(id.Value, _context);
                    if (customer != null)
                    {
                        if (string.IsNullOrEmpty(customer.CustomerRole))
                        {
                            return View("Error", new ErrorViewModel { RequestId = "Authorization Error - Cannot create new accounts for the user.User Role not assigned" });
                        }
                        else if (customer.CustomerRole == RoleEnum.Teller.ToString() || customer.CustomerRole == RoleEnum.Admin.ToString())
                        {
                            return View("Error", new ErrorViewModel { RequestId = "Authorization Error - Cannot create new accounts other than customers" });
                        }
                        else if (customer.CustomerNo != id.Value)
                        {
                            return View("Error", new ErrorViewModel { RequestId = "Authorization Error - access denied" });

                        }
                        header = $"Accounts : {customer.CustomerNo} / {customer.FirstName} {customer.LastName}";
                        TempData["CustomerNo"] = id;
                    }
                }
                else
                {
                    TempData["CustomerNo"] = null;
                }

                TempData["Header"] = header;

                var user = customerBl.GetAllCustomer(_context);
                ViewBag.OpenAccount = user != null && user.Count > 0 && user.Any(x => x.CustomerRole == RoleEnum.Customer.ToString());

                var accounts = accountbl.GetAllAccount(_context);

                
                if (id != null && accounts != null)
                {
                    accounts = accounts.Where(x => x.CustomerNo == id);

                }
                return View(accounts);
            }
            else
            {
                return RedirectToAction("Login", "Customers");
            }

        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Account
                .Include(a => a.Customer)
                .FirstOrDefaultAsync(m => m.AccountNo == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: Accounts/Create/{customerNo}
        public IActionResult OpenAccount(int? customerNo)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserRole")) || HttpContext.Session.GetString("UserRole") == RoleEnum.Customer.ToString())
            {
                return View("Error", new ErrorViewModel { RequestId = "Authorization Error - access denied" });
            }
            var id = TempData["CustomerNo"];
            TempData.Keep("CustomerNo");
            if (customerNo != null)
            {
                var customer = customerBl.GetCustomerFromCustomerNo(customerNo.Value,_context);
                if (customer == null || customer.CustomerRole == RoleEnum.Teller.ToString())
                {
                    return View("Error", new ErrorViewModel { RequestId = "Invalid Request - Cannot open new account for requested customer no." });
                }
            }

            var custList = GetAllCustomers()?.AsEnumerable();


            if (custList == null ||!custList.Any())
            {
                return View("Error", new ErrorViewModel { RequestId = "Invalid Request - Cannot open new account. Users not available/roles not mapped." });
            }
            string customerName = null;
            Account acc = new Account();
            acc.Interestrate = 0.02m;
            acc.AccountStatus = true;
            acc.Balance = 500.00m;
            if (id != null)
            {
                var customer = custList.FirstOrDefault(w => w.Value == id.ToString());
                if (customer != null)
                {
                    customerName = customer.Text;
                    acc.CustomerNo = int.Parse(customer.Value);
                }
            }

            ViewBag.CustomerName = customerName;
            ViewBag.CustList = custList;

            return View(acc);
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OpenAccount([Bind("Balance,AccountNo,AccountType,CustomerNo,AccountStatus,Interestrate")] Account account)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserRole")) || HttpContext.Session.GetString("UserRole") == RoleEnum.Customer.ToString())
            {
                return View("Error", new ErrorViewModel { RequestId = "Authorization Error - access denied" });
            }
            var customerNo = TempData["CustomerNo"];
            if (ModelState.IsValid)
            {
                account.AccountNo = accountbl.GenerateAccountno();

                if (account.AccountType == "Savings")
                {
                    var customer = customerBl.GetCustomerFromCustomerNo(account.CustomerNo, _context);
                    if (customer == null)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    ca = new SavingsAccount()
                    {
                        AccountNo = accountbl.GenerateAccountno(),
                        CustomerId = customer.Id,
                        CustomerNo = account.CustomerNo,
                        Balance = account.Balance,
                        AccountStatus = accountbl.GetAccountStatus(),
                        AccountType = account.AccountType,

                    };

                    ca.Interestrate = ca.GetIntrestrate();
                    accountbl.OpenAccount(ca, _context);

                }

                return RedirectToAction(nameof(Index), new { id = customerNo });

            }
            //ViewData["CustomerNo"] = new SelectList(_context.Customer, "CustomerNo", "Email", account.CustomerNo);
            return View(account);
        }

        // GET: Accounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserRole")) || HttpContext.Session.GetString("UserRole") == RoleEnum.Customer.ToString())
            {
                return View("Error", new ErrorViewModel { RequestId = "Authorization Error - access denied" });
            }
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Account.FindAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            ViewData["CustomerNo"] = new SelectList(_context.Customer, "CustomerNo", "Email", account.CustomerNo);
            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Balance,AccountNo,AccountType,CustomerNo,AccountStatus,MaturityDateTime,Interestrate")] Account account)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserRole")) || HttpContext.Session.GetString("UserRole") == RoleEnum.Customer.ToString())
            {
                return View("Error", new ErrorViewModel { RequestId = "Authorization Error - access denied" });
            }
            if (id != account.AccountNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(account);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.AccountNo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }

BankingWebApplication/Views/Customers/Create.cshtml
@model DAL.Entities.Customer

@{ ViewData["Title"] = "Create"; }

<link rel="stylesheet" href="~/css/ui.css">

<h2>Register</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">


            <div class="form-group">

                <label class="text-danger">@ViewBag.UserExistedMessage</label>


            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" placeholder="Enter User Name(length: 6-50)" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger">Enter User Name</span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" placeholder="Enter Password(Length: 0-63)" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" placeholder="Enter First Name" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" placeholder="Enter Last Name" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" placeholder="Enter Phone Number" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" placeholder="Enter Email Address" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" placeholder="Enter Home Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>



        </form>
    </div>
</div>



@*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BankingWebApplication/Views/Customers/Delete.cshtml
@model DAL.Entities.Customer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerNo" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BankingWebApplication/Views/Customers/Details.cshtml
@using Microsoft.AspNetCore.Http
@using DAL.Enum
@model DAL.Entities.Customer

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-customerno="@Model.CustomerNo">Edit</a>
    @if (string.IsNullOrEmpty(Context.Session.GetString("UserRole")) && Context.Session.GetString("UserRole") != RoleEnum.Customer.ToString())
    { 
        <span> | </span>
        <a asp-action="Index" style="font-size: medium;font-weight: bold">Back to List</a>
    }
</div>

BankingWebApplication/Views/Customers/Edit.cshtml
@using Microsoft.AspNetCore.Http
@using DAL.Enum
@model DAL.Entities.Customer

@{
    ViewData["Title"] = "Edit";
}

    <link rel="stylesheet" href="~/css/ui.css">
<h2>Edit</h2>
<h4>Personal Info</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CustomerNo" />
            <input type="hidden" asp-for="Password" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" style="background-color: black" readonly="readonly" />

            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>



        </form>
    </div>
</div>

@if (string.IsNullOrEmpty(Context.Session.GetString("UserRole")) && Context.Session.GetString("UserRole") != RoleEnum.Customer.ToString())
{ 
    <span> | </span>
    <a asp-action="Index" style="font-size: medium;font-weight: bold">Back to List</a>
}
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BankingWebApplication/Views/Customers/EditRole.cshtml
@model EditRoleViewModel

@{ ViewData["Title"] = "Edit Role"; }

<link rel="stylesheet" href="~/css/ui.css">
<h2>Edit Role</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditRole">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CustomerNo" class="control-label"></label>
                <input asp-for="CustomerNo" class="form-control" style="background-color: black" readonly="readonly" />
            </div>

            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" style="background-color: black" readonly="readonly" />
            </div>
            <div class="form-group">
                @foreach (var role in Model.RolesList)
                {
                    @Html.RadioButtonFor(m => m.SelectedRole, role.SelectedValue,new {@class = "control-label"}) <span> &nbsp;</span>

                    @Html.Label(role.SelectedValue.ToString(), role.SelectedValue.ToString(), new { @class = "control-label" })<span> &nbsp; &nbsp; &nbsp;</span>}

            </div>

            <div class="form-group">
                <input type="submit" value="Update Role" class="btn btn-default" />
            </div>



        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BankingWebApplication/Views/Customers/Index.cshtml
@using Microsoft.AspNetCore.Http
@using DAL.Enum
@model IEnumerable<DAL.Entities.Customer>

@{
    ViewData["Title"] = "Customers";
}

<h2>Customers</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerRole)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerRole)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
            @if (!string.IsNullOrEmpty(item.CustomerRole) && item.CustomerRole == RoleEnum.Customer.ToString())   
            {
                <a asp-controller="Accounts" asp-action="Index" asp-route-id="@item.CustomerNo" style="font-size: medium; font-weight: bold">Accounts</a>
                <span>&nbsp;| &nbsp; </span>
            }
                <a asp-action="Edit" asp-route-customerno="@item.CustomerNo" style="font-size: medium; font-weight: bold">Edit</a>
                <span>&nbsp;| &nbsp; </span>
                <a asp-action="Details" asp-route-id="@item.CustomerNo" style="font-size: medium; font-weight: bold">Details</a>
                @if (Context.Session.GetString("UserRole") != null && Context.Session.GetString("UserRole") == "Admin")
                {
                    <span>&nbsp;| &nbsp; </span>
                    <a asp-action="EditRole" asp-route-customerNo="@item.CustomerNo" asp-route-userName="@item.UserName" asp-route-roleName="@item.CustomerRole" style="font-size: medium; font-weight: bold">Edit User Roes</a>}
            </td>
        </tr>
            

        }
    </tbody>
</table>

BankingWebApplication/Views/Customers/LoggedInUserEdit.cshtml
@model DAL.Entities.Customer

@{
    ViewData["Title"] = "Edit";
}

    <link rel="stylesheet" href="~/css/ui.css">
<h2>Edit</h2>

<h4>Personal Info</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Customers" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerNo" />
            <input type="hidden" asp-for="Password" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" readonly="readonly" />

            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>



        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BankingWebApplication/Views/Customers/Login.cshtml
@model DAL.Entities.User

@{
    ViewData["Title"] = "Login";
}
    <link rel="stylesheet" href="~/css/ui.css">

<h2>Login</h2>

<body>
<div class="row">
    <div class="col-md-4 ">
        <form asp-action="Login">
            <div class="form-group">
                <label asp-for="UserName" label class="control-label">UserName</label>
                <input asp-for="UserName" class="form-control" placeholder="Enter User Name">
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label">Password</label>
                <input asp-for="Password" type="password" class="form-control" placeholder="Enter Passowrd">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <label class="label-success">@ViewBag.LoginSucceed</label>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <label class="label-danger">@ViewBag.LoginFailed</label>
                </div>
            </div>

          

        </form>
    </div>
 </div>

    </body>