BankingWebApplication/ViewComponents/NavigationViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BankingWebApplication.ViewComponents
{
    public class NavigationViewComponent : ViewComponent
    {
        public NavigationViewComponent()
        {

        }

        public IViewComponentResult Invoke() {

            var partialViewName = "_NavigationPublic";
            if (HttpContext.Session.GetString("CustomerNo") != null)
            {
                var role = HttpContext.Session.GetString("UserRole");
                if (!string.IsNullOrEmpty(role))
                {
                    if (role == RoleEnum.Admin.ToString())
                    {
                        partialViewName = "_NavigationAdmin";
                    }
                    else if (role == RoleEnum.Teller.ToString())
                    {
                        partialViewName = "_NavigationTeller";
                    }
                    else
                    {
                        partialViewName = "_NavigationCustomer";
                    }
                }

            }

            return View(partialViewName);
        }
    }
}

BankingWebApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankingWebApplication</title>
    
    @if (TempData["Message"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                var message = "@TempData["Message"]";
                $.notify(message, {
                    type: 'success',
                    icon: 'check',
                    align: "center",
                    verticalAlign: "top",
                    animation: true,
                    animationType: "drop",
                    close: true
                });
            };
        </script>
    }
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/ui.css" />
    </environment>
</head>
<body>
    
@await Component.InvokeAsync("Navigation", new { })


<partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Online Banking</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/notify.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/notify.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>